### PR TITLE
sql: Combine AND(Fixed, SQL) into a single IN clause, reducing roundtrips.…

### LINKED ISSUE #314: Optimize SQL Save()
Multiple chained Save() should only generate one SQL request instead of one SQL query per Save()

An example of the current behavior can be found here : [http://x.quentin-machu.fr/odeniqavef.json](http://x.quentin-machu.fr/odeniqavef.json)

### PR DESCRIPTION
**Pull request by barakmich**
… Add a test and benchmark.

Benchmarks on localhost:
The new test before:
```
BenchmarkSaveBogartPerformances	     200	   5916752 ns/op
```

The new test after:
```
BenchmarkSaveBogartPerformances	     500	   3431612 ns/op
```

So about 2x. Expect a bigger win when talking to a remote server.

Fixes #314

### CODE REVIEW

**Comment by Quentin-M** [comment]
It does not optimize every cases yet : http://x.quentin-machu.fr/neroqavelu.json

**Comment by Quentin-M** [comment]
LGTM.

Got 10x to 35x improvement from local <-> RDS ! Well done !

File: graph/sql/optimizers.go [hunk 1]
```diff
@@ -169,6 +172,32 @@ func (qs *QuadStore) optimizeLinksTo(it *iterator.LinksTo) (graph.Iterator, bool
...
 			return newIt, true
+		} else {
+			if !graph.Next(primary) {
+				panic("unexpected size during optimize")
+			}
+			val := primary.Result()
+			newIt := qs.QuadIterator(it.Direction(), val)
+			linkit := newIt.(*SQLIterator).sql.(*SQLLinkIterator)
+			if len(linkit.constraints) != 1 {
+				panic("constraint list should be only one, after fresh creation")
```
Comment (jzelinskie) [inline graph/sql/optimizers.go]: panics are prefaced with "packagename: " before the actual message

**Comment by Quentin-M** [comment]
SHEEP IT

(LGTM)
